---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fwten
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/fwten/flux-test
  ref:
    branch: main

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: stanni
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/St4NNi/gitops-demo2
  ref:
    branch: main

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fwten
  namespace: fwten
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: fwten
  path: ./test # Subpath in repo
  prune: false # Should resources be deleted

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stanni
  namespace: stanni
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: St4NNi
  path: ./test # Subpath in repo
  prune: false
